### Variables
@baseUrl = http://localhost:8080/api
@repoId = 69b9bada27b0b7690aea91a1
@ticketId = 69b9bba327b0b7690aea91a4

#Repo

# Create a new Repository
POST {{baseUrl}}/repositories
Content-Type: application/json

{
  "name": "E-Commerce Platform",
  "description": "Main backend microservices for the shopping cart and checkout",
  "key": "ECOUU",
  "ownerId": "user-123"
}

###
# get repo details
###
GET {{baseUrl}}/repositories/{{repoId}}
Content-Type: application/json

###

### Update repo version (daca sunt tickets deschise, nu se poate face update la versiune)
PATCH {{baseUrl}}/repositories/{{repoId}}/version
Content-Type: application/json

{
  "newVersion": "1.1.0",
  "releaseNotes": "Added the new payment gateway integration.",
  "updatedById": "user-456"
}


###
# 2. TICKETS
###

### tichet nou pt repo
POST {{baseUrl}}/tickets
Content-Type: application/json

{
  "title": "Payment gateway timeout",
  "description": "When users try to pay with credit card, the system times out after 30 seconds.",
  "repositoryId": "{{repoId}}",
  "assignedById": "tester-788"
}

###

### Get all Tickets for a Repository
GET {{baseUrl}}/tickets/repository/{{repoId}}
Content-Type: application/json

###

### Change Ticket Status
# statusuri OPEN, IN_EXECUTION, RESOLVED, CLOSED
PATCH {{baseUrl}}/tickets/{{ticketId}}/status
Content-Type: application/json

{
  "status": "OPEN"
}


###
# COMMENTS
###

### Add a Comment to a Ticket
POST {{baseUrl}}/comments
Content-Type: application/json

{
  "ticketId": "{{ticketId}}",
  "userId": "developer-101",
  "content": "I am looking into the timeout issue right now. It seems related to the third-party API."
}

###

### Get all Comments for a Ticket
GET {{baseUrl}}/comments/ticket/{{ticketId}}
Content-Type: application/json
